Repository EasileleM/gd-ui-react-project, pull requests merged in 2019-11, with the labels that each got.

#70 Newsletter form
  client/src/components/Newsletter/Newsletter.js
  client/src/components/Newsletter/Newsletter.scss
  client/src/components/Newsletter/assets/Mail_Ico_.png
  client/src/pages/home/index.js
  server/db/db.js
  server/pages/api/items.js
  server/pages/api/newsletter.js
  server/pages/api/slider/[id].js
Labels: back-end, front-end

#83 fixed image sizing
  client/src/components/ItemCardSmall/main.scss
  client/src/components/product-card/product-card.scss
Labels: front-end

#85 Fix/cart image bg
  client/src/components/SaleItem/main.scss
Labels: fix, front-end

#86 fix/newsletter
  client/src/components/Newsletter/Newsletter.js
  client/src/components/Newsletter/Newsletter.scss
Labels: front-end

#89 Fix/backend cors
  client/src/components/Newsletter/Newsletter.js
  server/package-lock.json
  server/pages/api/newsletter.js
Labels: back-end, front-end

#91 Fix cards
  client/src/components/ItemCardSmall/index.js
  client/src/components/product-catalog/product-catalog.js
Labels: fix, front-end

#92 Card content fix
  client/src/components/ItemCardSmall/main.scss
Labels: fix, front-end

#93 Fixed card rating
  client/src/components/ItemCardSmall/index.js
Labels: fix, front-end

#94 Slider text bold fix
  client/src/components/slider/item/main.scss
Labels: fix, front-end

#107 Font mixins
  client/src/components/AdsBlock/main.scss
  client/src/components/ItemCardSmall/main.scss
  client/src/components/Newsletter/Newsletter.scss
  client/src/components/SaleItem/main.scss
  client/src/components/footer/footer.scss
  client/src/components/header/header.scss
  client/src/components/slider/item/main.scss
  client/src/style/_fonts.scss
Labels: fix, front-end

#109 Special offer block refactor
  client/src/assets/bucket.png
  client/src/assets/square-1.svg
  client/src/assets/square-2.svg
  client/src/components/AdsBlock/main.scss
  client/src/components/SaleItem/index.js
  client/src/components/SaleItem/main.scss
  client/src/components/SpecialOfferSection/main.scss
Labels: front-end, refactor

#108 Refactored slider
  client/package-lock.json
  client/package.json
  client/src/components/ItemCardSmall/main.scss
  client/src/components/LoadingSpinner/index.js
  client/src/components/LoadingSpinner/main.scss
  client/src/components/index.js
  client/src/components/slider/Images/index.js
  client/src/components/slider/Images/main.scss
  client/src/components/slider/assets/Layer_1.png
  client/src/components/slider/buttons/main.scss
  client/src/components/slider/contentBlock/index.js
  client/src/components/slider/contentBlock/main.scss
  client/src/components/slider/imagesBlock/index.js
  client/src/components/slider/index.js
  client/src/components/slider/item/assets/bucket.png
  client/src/components/slider/item/main.scss
  client/src/components/slider/main.scss
  client/src/pages/home/main.scss
  client/src/style/_fonts.scss
  client/src/style/_mixins.scss
Labels: front-end, refactor

#111 Refactor/item card small
  client/src/components/ItemCardSmall/index.js
  client/src/components/ItemCardSmall/main.scss
Labels: front-end, refactor

#113 fixed slider endpoint
  server/db/db.js
  server/pages/api/slider/[id].js
  server/services/SliderService.js
Labels: back-end

#112 Small refactor in Slider and itemCardSmall
  client/src/assets/star-empty.svg
  client/src/assets/star.svg
  client/src/components/ItemCardSmall/assets/Add_To_Cart_Ico.png
  client/src/components/ItemCardSmall/index.js
  client/src/components/ItemCardSmall/main.scss
  client/src/components/slider/index.js
Labels: front-end, refactor

#118 Cards axios connection
  client/src/components/BestSalesBlock/index.js
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductSmallContainer/index.js
  client/src/pages/Home/index.js
  client/src/utils/index.js
  client/src/utils/loadCard.js
Labels: feature, front-end

#121 Tasks 103 and 120
  client/src/utils/loadCard.js
  server/db/db.js
  server/package-lock.json
  server/pages/api/items.js
  server/pages/api/items/pagination.js
  server/pages/api/items/recent.js
  server/pages/api/items/related.js
  server/pages/api/items/sales.js
  server/services/ItemsService.js
  server/services/SliderService.js
Labels: back-end, feature, front-end

#122 Pagination to sales, recent, related. items endpoint server-side validation.
  client/src/constants/index.js
  client/src/utils/loadCard.js
  client/src/utils/loadItem.js
  client/src/utils/loadSlides.js
  client/src/utils/sendEmail.js
  server/db/db.js
  server/pages/api/items.js
  server/pages/api/items/[id].js
  server/pages/api/items/all.js
  server/pages/api/items/recent.js
  server/pages/api/items/related.js
  server/pages/api/items/sales.js
  server/services/ItemsService.js
Labels: back-end, feature

#123 ✅ Feature/product-component
  client/src/components/Product/ProductImages/index.js
  client/src/components/Product/ProductImages/main.scss
  client/src/components/Product/ProductInfo/Chooser/index.js
  client/src/components/Product/ProductInfo/Chooser/main.scss
  client/src/components/Product/ProductInfo/assets/cart.png
  client/src/components/Product/ProductInfo/assets/like.png
  client/src/components/Product/ProductInfo/assets/share.png
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/ProductInfo/main.scss
  client/src/components/Product/index.js
  client/src/components/Product/main.scss
  client/src/style/_breakpoints.scss
  client/src/style/_mixins.scss
Labels: feature, front-end

#124 Feature/103+120
  client/src/utils/loadItem.js
  server/db/db.js
  server/pages/api/items.js
  server/pages/api/items/[id].js
  server/pages/api/items/recent.js
  server/pages/api/items/related.js
  server/pages/api/items/sales.js
  server/services/ItemsService.js
Labels: back-end, feature, fix, refactor

#125 Load-more button loading indicator
  client/src/assets/dots.svg
  client/src/assets/loadingDots.svg
  client/src/components/ProductCatalog/ShowMoreButton/index.js
  client/src/components/ProductCatalog/ShowMoreButton/main.scss
  client/src/components/ProductCatalog/index.js
Labels: feature, front-end

#127 Loading indicator fix
  client/src/components/ProductCatalog/ShowMoreButton/index.js
  client/src/components/ProductCatalog/index.js
  client/src/utils/loadCard.js
  client/src/utils/loadItem.js
Labels: fix, front-end

#132 feature/card links
  client/src/components/ItemCardSmall/index.js
  client/src/components/ProductCard/index.js
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductSmallContainer/index.js
  client/src/components/ProductsContainer/index.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.scss
Labels: feature, front-end

#131 feature/popup creation logic
  client/src/components/Newsletter/index.js
  client/src/components/Popups/index.js
  client/src/components/Popups/main.scss
Labels: feature, front-end

#133 fix/language specific requests
  server/db/db.js
  server/pages/api/slider.js
  server/services/ItemsService.js
  server/services/SliderService.js
Labels: back-end, fix

#135 feature/slider-links
  client/src/components/Product/ProductInfo/main.scss
  client/src/components/Slider/ContentBlock/index.js
  client/src/components/Slider/Item/index.js
Labels: feature, front-end

#137 Feature/related products
  client/public/locales/en-GB/translation.json
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/Product/ProductImages/main.scss
  client/src/components/Product/ProductInfo/Chooser/index.js
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/ProductInfo/main.scss
  client/src/components/ProductCard/main.scss
  client/src/components/ProductCatalogRow/ProductCatalogRow.jsx
  client/src/components/ProductCatalogRow/ProductCatalogRow.scss
  client/src/components/RelatedProductsBlock/RelatedProductsBlock.jsx
  client/src/components/RelatedProductsBlock/RelatedProductsBlock.scss
  client/src/components/SectionHeader/main.scss
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.scss
  client/src/utils/loadRelated.js
Labels: feature, front-end

#136 fix/connection-pool
  server/db/db.js
Labels: back-end, fix

#139 Downloading translated data from server
  client/src/components/Header/ChangeLanguageButton.jsx
  client/src/utils/loadCard.js
  client/src/utils/loadItem.js
  client/src/utils/loadItemSales.js
  client/src/utils/loadSlides.js
Labels: feature, front-end

#141 Cart. Feature 103.
  client/src/assets/removeButton.svg
  client/src/components/BestSalesBlock/index.js
  client/src/components/CartWindow/CartWindow.jsx
  client/src/components/CartWindow/CartWindow.scss
  client/src/components/CartWindow/CloseButton/CloseButton.jsx
  client/src/components/CartWindow/CloseButton/CloseButton.scss
  client/src/components/CartWindow/Items/Item/Item.jsx
  client/src/components/CartWindow/Items/Item/Item.scss
  client/src/components/CartWindow/Items/Items.jsx
  client/src/components/CartWindow/Items/Items.scss
  client/src/components/CartWindow/OrderBlock/OrderBlock.jsx
  client/src/components/CartWindow/OrderBlock/OrderBlock.scss
  client/src/components/Header/cart.js
  client/src/components/Header/index.js
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
  client/src/components/ItemCardSmall/index.js
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/Product/ProductInfo/index.js
  client/src/components/ProductCard/AddToCartButton/index.js
  client/src/components/ProductCard/ColorSelector/index.js
  client/src/components/ProductCard/SizesSelector/index.js
  client/src/components/ProductCard/index.js
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductSmallContainer/index.js
  client/src/components/ProductsContainer/index.js
  client/src/components/SaleItem/index.js
  client/src/components/SpecialOfferSection/index.js
  client/src/index.scss
  client/src/pages/Home/Home.js
  client/src/pages/Home/index.js
  client/src/pages/Layout/Layout.js
  client/src/pages/Layout/index.js
  client/src/pages/index.js
  client/src/utils/changeBodyScrollState.js
  client/src/utils/index.js
  client/src/utils/loadIdArray.js
Labels: feature, front-end

#140 Fix/mobile version layout
  client/src/components/Footer/banking.js
  client/src/components/Footer/links.js
  client/src/components/Footer/main.scss
  client/src/components/Header/ChangeLanguageButton.scss
  client/src/components/Header/contacts.js
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
  client/src/components/Popups/main.scss
Labels: feature, front-end

#144 feature: interceptor, popups
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Product/index.js
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductCatalogRow/ProductCatalogRow.jsx
  client/src/components/ProductSmallContainer/index.js
  client/src/components/SaleItem/index.js
  client/src/components/Slider/index.js
  client/src/pages/Layout/Layout.js
  client/src/utils/interceptorResponse.js
Labels: feature, front-end

#145 Feature/Link in header
  client/src/App.js
  client/src/components/Header/navigation.js
  client/src/components/Product/ProductInfo/Chooser/main.scss
  client/src/components/Product/ProductInfo/main.scss
  client/src/components/SectionHeader/ScrollOnTop.js
  client/src/pages/Layout/Layout.js
Labels: feature, front-end

#146 linked cart with pdp
  client/src/components/ItemCardSmall/index.js
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/index.js
  client/src/components/ProductCatalogRow/ProductCatalogRow.jsx
  client/src/components/RelatedProductsBlock/RelatedProductsBlock.jsx
  client/src/pages/Layout/Layout.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.js
Labels: fix, front-end

#147 Fix/related-products
  client/src/components/Product/ProductImages/index.js
  client/src/components/Product/ProductInfo/Chooser/main.scss
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/ProductInfo/main.scss
  client/src/components/Product/index.js
Labels: fix, front-end

#148 Fix/header navigation
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
Labels: fix, front-end

#151 Fix related
  server/services/ItemsService.js
Labels: back-end, fix

#153 merge master
  client/src/pages/Home/index.js
  client/src/pages/index.js
Labels: refactor

#156 fix/pdp-markup
  client/package-lock.json
  client/src/components/Product/ProductImages/index.js
  client/src/components/Product/ProductImages/main.scss
  client/src/components/Product/ProductInfo/Chooser/index.js
  client/src/components/Product/ProductInfo/Chooser/main.scss
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/ProductInfo/main.scss
Labels: fix, front-end

#157 fix/newsletter-markup
  client/src/components/Newsletter/main.scss
Labels: fix, front-end

#159 feature/redux
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/error-actions.js
  client/src/actions/types.js
  client/src/pages/Layout/Layout.js
  client/src/pages/errors/404/NotFound.js
  client/src/pages/errors/404/NotFound.scss
  client/src/reducers/errorReducer.js
  client/src/reducers/index.js
  client/src/store.js
  client/src/utils/interceptorResponse.js
Labels: feature, front-end

#158 fixed and refactored slider
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/Slider/Buttons/index.js
  client/src/components/Slider/Buttons/main.scss
  client/src/components/Slider/ContentBlock/index.js
  client/src/components/Slider/Images/index.js
  client/src/components/Slider/index.js
  client/src/constants/index.js
  client/src/pages/Layout/Layout.js
  client/src/pages/Layout/index.js
Labels: fix, front-end, refactor

#170 fixed filter logic
  server/services/ItemsService.js
Labels: back-end, fix

#173 svg logo added
  client/src/assets/basket-linear.svg
  client/src/assets/logo-ellipse.svg
  client/src/assets/shopping-basket.svg
  client/src/components/Header/cart.js
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
  client/src/style/_colors.scss
  client/src/style/_fonts.scss
  client/src/style/_mixins.scss
Labels: front-end, refactor

#174 Fix filter logic
  server/services/ItemsService.js
Labels: back-end, fix

#172 Cart refactor
  client/package-lock.json
  client/package.json
  client/src/action-creators/cart-action-creator.js
  client/src/action-creators/error-action-creator.js
  client/src/actions/cart-actions.js
  client/src/actions/error-actions.js
  client/src/actions/types.js
  client/src/components/BestSalesBlock/index.js
  client/src/components/CartWindow/CartWindow.jsx
  client/src/components/CartWindow/CartWindow.scss
  client/src/components/CartWindow/CloseButton/CloseButton.jsx
  client/src/components/CartWindow/CloseButton/CloseButton.scss
  client/src/components/CartWindow/Items/Item/Item.jsx
  client/src/components/CartWindow/Items/Item/Item.scss
  client/src/components/CartWindow/Items/Items.jsx
  client/src/components/CartWindow/Items/Items.scss
  client/src/components/CartWindow/OrderBlock/OrderBlock.jsx
  client/src/components/CartWindow/OrderBlock/OrderBlock.scss
  client/src/components/Header/cart.js
  client/src/components/Header/index.js
  client/src/components/Header/navigation.js
  client/src/components/ItemCardSmall/index.js
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/index.js
  client/src/components/ProductCard/AddToCartButton/index.js
  client/src/components/ProductCard/index.js
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductCatalogRow/ProductCatalogRow.jsx
  client/src/components/ProductSmallContainer/index.js
  client/src/components/ProductsContainer/index.js
  client/src/components/RelatedProductsBlock/RelatedProductsBlock.jsx
  client/src/components/SaleItem/index.js
  client/src/components/SpecialOfferSection/index.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/index.js
  client/src/pages/Home/main.scss
  client/src/pages/Layout/Layout.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.js
  client/src/reducers/cartReducer.js
  client/src/reducers/index.js
  client/src/store.js
  client/src/utils/cart/addItem.js
  client/src/utils/cart/fetchItems.js
  client/src/utils/cart/removeItem.js
  client/src/utils/cart/updateItem.js
  client/src/utils/interceptorResponse.js
  client/src/utils/localStorage/getLocalStorageCollection.js
  client/src/utils/localStorage/updateLocalStorageCollection.js
Labels: feature, fix, front-end, refactor

#175 support + as spaces in query
  server/services/ItemsService.js
Labels: back-end, fix

#177 Feature/filters
  client/package-lock.json
  client/package.json
  client/src/action-creators/filter-action-creator.js
  client/src/actions/filter-actions.js
  client/src/actions/types.js
  client/src/assets/controls.svg
  client/src/assets/delete.svg
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/FIlterSlider/FilterSlider.scss
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.js
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.scss
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/FilterRadio/FilterRadio.scss
  client/src/components/Filters/Filters.js
  client/src/components/Filters/Filters.scss
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/Newsletter/main.scss
  client/src/components/Product/ProductImages/index.js
  client/src/components/ProductCard/index.js
  client/src/components/ProductCard/main.scss
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductsContainer/index.js
  client/src/components/ProductsContainer/main.scss
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/pages/Search/Search.scss
  client/src/reducers/filterReducer.js
  client/src/reducers/index.js
  client/src/style/_colors.scss
  client/src/utils/cart/changeItem.js
  client/src/utils/cart/updateLocalStorage.js
  client/src/utils/loadCard.js
  client/src/utils/loadFilters.js
Labels: feature, front-end

#178 fix: notifications logic
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductCatalogRow/ProductCatalogRow.jsx
  client/src/components/ProductSmallContainer/index.js
  client/src/components/SaleItem/index.js
  client/src/components/Slider/index.js
  client/src/reducers/cartReducer.js
  client/src/utils/cart/addItem.js
  client/src/utils/cart/removeItem.js
  client/src/utils/cart/updateItem.js
  client/src/utils/interceptorResponse.js
  client/src/utils/notificationError.js
  client/src/utils/notificationSuccess.js
Labels: fix, front-end

#179 errors handling
  client/src/action-creators/error-action-creator.js
  client/src/actions/error-actions.js
  client/src/actions/types.js
  client/src/pages/Layout/Layout.js
  client/src/pages/errors/404/NotFound.js
  client/src/pages/errors/ErrorPage.jsx
  client/src/pages/errors/ErrorPage.scss
  client/src/reducers/errorReducer.js
  client/src/utils/interceptorResponse.js
  client/src/utils/notificationError.js
Labels: feature, front-end

#176 Favorites
  client/src/action-creators/favorites-action-creator.js
  client/src/actions/favorites-actions.js
  client/src/actions/types.js
  client/src/assets/likeDisabled.svg
  client/src/assets/likeEnabled.svg
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.scss
  client/src/components/CartItems/CartItems.jsx
  client/src/components/CartItems/CartItems.scss
  client/src/components/CartItems/Item/Item.jsx
  client/src/components/CartItems/Item/Item.scss
  client/src/components/CartWindow/CartWindow.jsx
  client/src/components/FavoritesItems/FavoritesItems.jsx
  client/src/components/FavoritesItems/FavoritesItems.scss
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/FavoritesItems/Item/Item.scss
  client/src/components/Header/navigation.js
  client/src/components/ModalWindow/CloseButton/CloseButton.jsx
  client/src/components/ModalWindow/CloseButton/CloseButton.scss
  client/src/components/ModalWindow/ModalWindow.jsx
  client/src/components/ModalWindow/ModalWindow.scss
  client/src/components/OrderBlock/OrderBlock.jsx
  client/src/components/OrderBlock/OrderBlock.scss
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/ProductInfo/main.scss
  client/src/components/ProductCard/AddToFavoriteButton/index.js
  client/src/components/ProductCard/AddToFavoriteButton/main.scss
  client/src/components/ProductCard/index.js
  client/src/components/ProductsContainer/index.js
  client/src/pages/Layout/Layout.js
  client/src/reducers/favoritesReducer.js
  client/src/reducers/index.js
  client/src/utils/favorites/addItem.js
  client/src/utils/favorites/fetchItems.js
  client/src/utils/favorites/removeItem.js
  server/services/ItemsService.js
Labels: feature, front-end

#183 feature: dependicies for tests
  client/package-lock.json
  client/package.json
Labels: feature

#184 Hover and focus effects in add to favorites button
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.scss
Labels: feature, front-end

#185 fix: notifications
  client/src/utils/cart/removeItem.js
  client/src/utils/cart/updateItem.js
Labels: fix

#187 cart and favorites translation
  client/src/utils/loadIdArray.js
Labels: fix, front-end

#186 cart and favorites translation
  client/public/locales/en-GB/translation.json
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/CartItems/Item/Item.jsx
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/OrderBlock/OrderBlock.jsx
Labels: feature, front-end

#182 fix/slider-thumbs
  client/src/components/Filters/FIlterSlider/FilterSlider.js
Labels: fix, front-end

#188 Refactor/add svg images
  client/src/assets/favorite_border-24px.svg
  client/src/components/Footer/index.js
  client/src/components/Footer/links.js
  client/src/components/Footer/main.scss
  client/src/components/Header/cart.js
  client/src/components/Header/contacts.js
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
  client/src/components/Header/user.js
  client/src/components/Logo/index.js
  client/src/components/Logo/main.scss
  client/src/style/_breakpoints.scss
Labels: front-end, refactor

#189 Unit tests for redux reducers
  client/src/action-creators/cart-action-creator.js
  client/src/reducers/cartReducer.js
  client/src/reducers/cartReducer.spec.js
  client/src/reducers/errorReducer.js
  client/src/reducers/errorReducer.spec.js
  client/src/reducers/favoritesReducer.js
  client/src/reducers/favoritesReduces.spec.js
  client/src/reducers/filterReducer.js
  client/src/reducers/filterReducer.spec.js
  client/src/reducers/index.js
Labels: feature, front-end

#191 notification favorites
  client/src/utils/favorites/addItem.js
  client/src/utils/notificationError.js
Labels: feature, front-end

#190 feature/search
  client/src/action-creators/filter-action-creator.js
  client/src/actions/filter-actions.js
  client/src/actions/types.js
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/Filters.js
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
  client/src/components/Newsletter/main.scss
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/pages/Search/Search.scss
  client/src/reducers/filterReducer.js
  client/src/utils/loadCard.js
Labels: feature, front-end

#194 notifications for favourites is empty
  client/src/reducers/favoritesReducer.js
Labels: fix, front-end

#196 Feature/backend search api
  server/db/db.js
  server/pages/api/items/all.js
  server/services/ItemsService.js
Labels: back-end, feature

#197 Fix/backend search api
  server/services/ItemsService.js
Labels: back-end, fix

#198 Feature/utils tests
  client/package.json
  client/src/components/Popups/index.js
  client/src/components/Popups/main.scss
  client/src/reducers/cartReducer.spec.js
  client/src/reducers/errorReducer.spec.js
  client/src/reducers/favoritesReduces.spec.js
  client/src/utils/cart/changeItem.js
  client/src/utils/cart/removeItem.js
  client/src/utils/cart/tests/addItem.spec.js
  client/src/utils/cart/tests/fetchItems.spec.js
  client/src/utils/cart/tests/removeItem.spec.js
  client/src/utils/cart/tests/updateItem.spec.js
  client/src/utils/cart/updateItem.js
  client/src/utils/cart/updateLocalStorage.js
  client/src/utils/favorites/fetchItems.js
  client/src/utils/favorites/tests/addItem.spec.js
  client/src/utils/favorites/tests/fetchItems.spec.js
  client/src/utils/favorites/tests/removeItem.spec.js
  client/src/utils/localStorage/tests/getLocalStorageCollection.spec.js
Labels: feature, front-end

#199 Markup fixes
  client/public/locales/ru/translation.json
  client/src/components/CartItems/CartItems.scss
  client/src/components/CartItems/Item/Item.scss
  client/src/components/FavoritesItems/FavoritesItems.scss
  client/src/components/FavoritesItems/Item/Item.scss
  client/src/components/ItemCardSmall/main.scss
  client/src/components/ProductCard/main.scss
  client/src/components/ProductCatalog/ShowMoreButton/main.scss
  client/src/components/ProductsContainer/main.scss
  client/src/components/SaleItem/main.scss
  client/src/components/SpecialOfferSection/main.scss
  client/src/index.scss
Labels: fix, front-end

#200 Fix/markup
  client/package.json
  client/src/action-creators/filter-action-creator.js
  client/src/actions/filter-actions.js
  client/src/actions/types.js
  client/src/assets/delete.svg
  client/src/assets/likeDisabled.svg
  client/src/assets/loupe.svg
  client/src/assets/not-found.svg
  client/src/assets/search.svg
  client/src/assets/share.svg
  client/src/assets/shopping-basket1.svg
  client/src/assets/shopping-cart-add.svg
  client/src/assets/user.svg
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.scss
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.scss
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/FilterRadio/FilterRadio.scss
  client/src/components/Filters/FilterSearchBar/FilterSearchBar.js
  client/src/components/Filters/FilterSearchBar/FilterSearchBar.scss
  client/src/components/Filters/Filters.js
  client/src/components/Filters/Filters.scss
  client/src/components/Header/cart.js
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
  client/src/components/Newsletter/Newsletter.js
  client/src/components/Newsletter/Newsletter.scss
  client/src/components/ProductCard/AddToCartButton/index.js
  client/src/components/ProductCard/AddToCartButton/main.scss
  client/src/components/ProductCard/index.js
  client/src/components/ProductCard/main.scss
  client/src/components/ProductCatalog/index.js
  client/src/components/ProductCatalog/main.scss
  client/src/components/index.js
  client/src/pages/Home/Home.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.js
  client/src/pages/Search/Search.js
  client/src/pages/Search/Search.scss
  client/src/reducers/filterReducer.js
  client/src/reducers/filterReducer.spec.js
  client/src/style/_mixins.scss
  client/src/utils/__tests__/loadCard.spec.js
  client/src/utils/__tests__/loadFilters.cpec.js
  client/src/utils/__tests__/loadIdArray.spec.js
  client/src/utils/__tests__/loadItem.spec.js
  client/src/utils/__tests__/loadItemSales.spec.js
  client/src/utils/__tests__/loadRelated.spec.js
  client/src/utils/__tests__/loadSlides.spec.js
Labels: fix, front-end

#202 added links to cart items
  client/src/components/CartItems/Item/Item.jsx
Labels: fix, front-end

#203 fixes/markup-pdp
  client/src/components/Header/main.scss
  client/src/components/Product/ProductInfo/Chooser/index.js
  client/src/components/Product/ProductInfo/Chooser/main.scss
  client/src/components/Product/ProductInfo/index.js
  client/src/components/Product/ProductInfo/main.scss
  client/src/utils/loadCard.js
Labels: fix, front-end

#205 feature: filters translation
  client/public/locales/en-GB/translation.json
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/Filters/Filters.js
  client/src/components/ProductCatalog/index.js
Labels: feature, front-end

#206 fixed some markup
  client/package-lock.json
  client/package.json
  client/src/components/Header/navigation.js
  client/src/components/ProductCatalog/index.js
  client/src/pages/Search/Search.js
  client/src/pages/Search/Search.scss
  client/src/utils/__tests__/loadCard.spec.js
  client/src/utils/__tests__/loadFilters.spec.js
Labels: fix, front-end

#214 test/newsletter
  client/package-lock.json
  client/package.json
  client/src/components/Newsletter/Newsletter.js
  client/src/components/Newsletter/Newsletter.spec.js
  client/src/components/index.js
  client/src/pages/Home/Home.js
  client/src/pages/ProductDescriptionPage/ProductDescriptionPage.js
  client/src/pages/Search/Search.js
Labels: front-end, test

#217 fix/search-urls
  client/package-lock.json
  client/package.json
  client/src/components/Header/navigation.js
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/ProductCatalog/index.js
  client/src/pages/Search/Search.js
  package-lock.json
Labels: fix, front-end

#219 fix/url-reset-search
  client/src/components/Header/navigation.js
Labels: fix, front-end

#220 fix for submit
  client/src/components/Header/navigation.js
Labels: fix, front-end

#222 Fix/search submit
  client/src/components/Header/main.scss
  client/src/components/Header/navigation.js
Labels: fix, front-end

#223 fixes/tests
  client/src/components/index.js
  client/src/pages/Search/Search.spec.js
Labels: fix, front-end

#225 Tests for logo
  client/src/components/Logo/Logo.js
  client/src/components/Logo/Logo.spec.js
Labels: front-end, test

#224 small slider fix
  client/src/components/Slider/Buttons/index.js
Labels: fix, front-end

#226 Footer && header naming changed
  client/src/components/Footer/Footer.js
  client/src/components/Header/Header.js
  client/src/components/Header/navigation.js
  client/src/components/Header/user.js
  client/src/pages/Layout/Layout.js
Labels: fix, front-end

#227 Test/footer
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.spec.js
  client/src/reducers/errorReducer.spec.js
  client/src/utils/cart/tests/addItem.spec.js
Labels: front-end, test

#230 fixes/tests
  client/src/components/Filters/Filters.js
  client/src/components/Filters/Filters.spec.js
  client/src/components/Newsletter/Newsletter.spec.js
Labels: fix, front-end, test

#231 Tests/components
  client/src/components/CartItems/Item/tests/Item.spec.js
  client/src/components/CartItems/tests/CartItems.spec.js
  client/src/components/FavoritesItems/Item/tests/Item.spec.js
  client/src/components/FavoritesItems/tests/FavoritesItems.spec.js
  client/src/components/ProductCard/index.js
  client/src/components/ProductCard/tests/index.spec.js
Labels: front-end, test

#233 Tests/product
  client/src/components/Product/ProductImages/ProductImages.js
  client/src/components/Product/ProductImages/ProductImages.spec.js
  client/src/components/Product/ProductInfo/ProductInfo.spec.js
Labels: front-end, test

#235 tests/navigation
  client/src/components/Header/__tests__/navigation.spec.js
  client/src/components/Product/ProductInfo/Chooser/Chooser.js
Labels: front-end, test

#236 feature: replace old translation to hoc's
  client/public/locales/en-GB/translation.json
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/BestSalesBlock/index.js
  client/src/components/Filters/Filters.js
  client/src/components/Footer/banking.js
  client/src/components/Footer/links.js
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/ProductCard/SizesSelector/SizesSelector.spec.js
  client/src/components/ProductCard/SizesSelector/index.js
  client/src/components/ProductCard/index.js
  client/src/components/ProductCatalog/index.js
  client/src/components/RelatedProductsBlock/RelatedProductsBlock.jsx
  client/src/pages/Home/Home.js
Labels: fix, front-end

#237 fix:svg optimize
  client/src/assets/basket-linear.svg
  client/src/assets/controls.svg
  client/src/assets/delete.svg
  client/src/assets/search.svg
  client/src/assets/share.svg
  client/src/assets/shopping-basket.svg
Labels: fix

#245 Minimize svg
  client/src/assets/basket-linear.svg
  client/src/assets/controls.svg
  client/src/assets/delete.svg
  client/src/assets/search.svg
  client/src/assets/share.svg
  client/src/assets/shopping-basket.svg
Labels: fix

#246 tests/product-catalog
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/ProductCatalog/ProductCatalog.js
  client/src/components/ProductCatalog/ProductCatalog.scss
  client/src/components/ProductCatalog/ProductCatalog.spec.js
  client/src/pages/Search/Search.js
Labels: front-end, test

#247 Feature/filters url
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.js
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/Filters.js
  client/src/components/Header/navigation.js
  client/src/components/ProductCatalog/ProductCatalog.js
  client/src/pages/Search/Search.js
  client/src/utils/loadCard.js
Labels: feature, front-end

#248 cart fix
  client/src/components/OrderBlock/OrderBlock.jsx
Labels: fix, front-end

#266 refactored redux folders
  client/src/App.js
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/CartItems/Item/Item.jsx
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.js
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/FilterSearchBar/FilterSearchBar.js
  client/src/components/Filters/Filters.js
  client/src/components/Header/cart.js
  client/src/components/Header/navigation.js
  client/src/components/ItemCardSmall/index.js
  client/src/components/Product/ProductInfo/ProductInfo.js
  client/src/components/ProductCard/AddToCartButton/index.js
  client/src/components/SaleItem/index.js
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/redux/action-creators/cart-action-creator.js
  client/src/redux/action-creators/error-action-creator.js
  client/src/redux/action-creators/favorites-action-creator.js
  client/src/redux/action-creators/filter-action-creator.js
  client/src/redux/actions/cart-actions.js
  client/src/redux/actions/error-actions.js
  client/src/redux/actions/favorites-actions.js
  client/src/redux/actions/filter-actions.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/cartReducer.js
  client/src/redux/reducers/cartReducer.spec.js
  client/src/redux/reducers/errorReducer.js
  client/src/redux/reducers/errorReducer.spec.js
  client/src/redux/reducers/favoritesReducer.js
  client/src/redux/reducers/favoritesReduces.spec.js
  client/src/redux/reducers/filterReducer.js
  client/src/redux/reducers/filterReducer.spec.js
  client/src/redux/reducers/index.js
  client/src/redux/store.js
  client/src/redux/thunks/cart/addItem.js
  client/src/redux/thunks/cart/fetchItems.js
  client/src/redux/thunks/cart/removeItem.js
  client/src/redux/thunks/cart/tests/addItem.spec.js
  client/src/redux/thunks/cart/tests/fetchItems.spec.js
  client/src/redux/thunks/cart/tests/removeItem.spec.js
  client/src/redux/thunks/cart/tests/updateItem.spec.js
  client/src/redux/thunks/cart/updateItem.js
  client/src/redux/thunks/favorites/addItem.js
  client/src/redux/thunks/favorites/fetchItems.js
  client/src/redux/thunks/favorites/removeItem.js
  client/src/redux/thunks/favorites/tests/addItem.spec.js
  client/src/redux/thunks/favorites/tests/fetchItems.spec.js
  client/src/redux/thunks/favorites/tests/removeItem.spec.js
  client/src/utils/interceptorResponse.js
Labels: front-end, refactor

#265 fixed favorite button indicator
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/ProductCard/index.js
Labels: fix, front-end

#264 fix/product-card-front-image
  client/src/components/ProductCard/ProductCard.js
  client/src/components/ProductCard/ProductCard.scss
  client/src/components/ProductCard/__tests__/index.spec.js
  client/src/components/ProductsContainer/ProductsContainer.js
Labels: fix, front-end

#268 refactored redux logic for better scalability
  client/package-lock.json
  client/package.json
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/CartItems/CartItems.jsx
  client/src/components/CartItems/Item/Item.jsx
  client/src/components/FavoritesItems/FavoritesItems.jsx
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/Filters.js
  client/src/components/Header/cart.js
  client/src/components/Header/navigation.js
  client/src/components/ModalWindow/ModalWindow.jsx
  client/src/components/Product/Product.js
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/redux/action-creators/cart-action-creator.js
  client/src/redux/action-creators/favorites-action-creator.js
  client/src/redux/action-creators/modalWindow-action-creator.js
  client/src/redux/action-types/cartActionTypes.js
  client/src/redux/action-types/errorActionTypes.js
  client/src/redux/action-types/favoritesActionTypes.js
  client/src/redux/action-types/filterActionTypes.js
  client/src/redux/action-types/modalWindowActionTypes.js
  client/src/redux/actions/cart-actions.js
  client/src/redux/actions/error-actions.js
  client/src/redux/actions/favorites-actions.js
  client/src/redux/actions/filter-actions.js
  client/src/redux/actions/modalWindow-action.js
  client/src/redux/actions/types.js
  client/src/redux/reducers/cartReducer.js
  client/src/redux/reducers/errorReducer.js
  client/src/redux/reducers/favoritesReducer.js
  client/src/redux/reducers/filterReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/modalWindowReducer.js
  client/src/utils/changeBodyScrollState.js
Labels: front-end, refactor

#272 search value corresponds current uri
  client/src/components/Header/navigation.js
Labels: fix, front-end

#270 fixed nav menu toggle
  client/src/components/Header/navigation.js
Labels: fix, front-end

#275 fixed saleItem add to cart functionality
  client/src/components/SaleItem/index.js
Labels: fix, front-end

#276 feature/srcset
  client/src/components/ItemCardSmall/ItemCardSmall.js
  client/src/components/ItemCardSmall/ItemCardSmall.scss
  client/src/components/ItemCardSmall/tests/ItemCardSmall.spec.js
  client/src/components/Product/ProductImages/ProductImages.js
  client/src/components/ProductCard/ProductCard.js
  client/src/components/ProductSmallContainer/ProductSmallContainer.js
  client/src/components/SaleItem/SaleItem.js
  client/src/components/SaleItem/SaleItem.scss
  client/src/components/SaleItem/tests/index.spec.js
  client/src/components/Slider/Buttons/Buttons.js
  client/src/components/Slider/Buttons/Buttons.scss
  client/src/components/Slider/Buttons/__tests__/Buttons.spec.js
  client/src/components/Slider/ContentBlock/ContentBlock.js
  client/src/components/Slider/ContentBlock/ContentBlock.scss
  client/src/components/Slider/ContentBlock/__tests__/ContentBlock.spec.js
  client/src/components/Slider/Images/index.js
  client/src/components/Slider/index.js
  client/src/components/Slider/main.scss
  client/src/components/SpecialOfferSection/SpecialOfferSection.js
  client/src/components/SpecialOfferSection/SpecialOfferSection.scss
  client/src/constants/constants.js
  client/src/pages/Home/Home.js
  client/src/utils/__tests__/loadCard.spec.js
  client/src/utils/__tests__/loadFilters.spec.js
  client/src/utils/__tests__/loadIdArray.spec.js
  client/src/utils/__tests__/loadItem.spec.js
  client/src/utils/__tests__/loadItemSales.spec.js
  client/src/utils/__tests__/loadRelated.spec.js
  client/src/utils/__tests__/loadSlides.spec.js
  client/src/utils/loadCard.js
  client/src/utils/loadFilters.js
  client/src/utils/loadIdArray.js
  client/src/utils/loadItem.js
  client/src/utils/loadItemSales.js
  client/src/utils/loadRelated.js
  client/src/utils/loadSlides.js
  client/src/utils/sendEmail.js
Labels: feature, front-end

#278 Front end implimentation of user authorization
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/AddToCartButton/AddToCartButton.jsx
  client/src/components/AddToCartButton/AddToCartButton.scss
  client/src/components/CartItems/CartItems.jsx
  client/src/components/CartItems/Item/Item.jsx
  client/src/components/CartItems/Item/Item.scss
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/FavoritesItems/Item/Item.scss
  client/src/components/Header/Header.jsx
  client/src/components/Header/Header.scss
  client/src/components/Header/UserButton/UserButton.jsx
  client/src/components/Header/cart.jsx
  client/src/components/Header/contacts.jsx
  client/src/components/Header/navigation.jsx
  client/src/components/LoginWindowContent/InvalidFormNotification/InvalidFormNotification.jsx
  client/src/components/LoginWindowContent/InvalidFormNotification/InvalidFormNotification.scss
  client/src/components/LoginWindowContent/LoginWindowContent.jsx
  client/src/components/LoginWindowContent/LoginWindowContent.scss
  client/src/components/LoginWindowContent/LoginWindowContentControls/LoginWindowContentControls.jsx
  client/src/components/LoginWindowContent/LoginWindowContentControls/LoginWindowContentControls.scss
  client/src/components/LoginWindowContent/LoginWindowFormButton/LoginWindowFormButton.jsx
  client/src/components/LoginWindowContent/LoginWindowFormButton/LoginWindowFormButton.scss
  client/src/components/LoginWindowContent/SignInForm/SignInForm.jsx
  client/src/components/LoginWindowContent/SignUpForm/SignUpForm.jsx
  client/src/components/ModalWindow/CloseButton/CloseButton.jsx
  client/src/components/ModalWindow/ModalWindow.scss
  client/src/components/ModalWindowWrapper/CloseButton/CloseButton.jsx
  client/src/components/ModalWindowWrapper/CloseButton/CloseButton.scss
  client/src/components/ModalWindowWrapper/CloseButton/tests/CloseButton.spec.js
  client/src/components/ModalWindowWrapper/ModalWindow/ModalWindow.jsx
  client/src/components/ModalWindowWrapper/ModalWindow/ModalWindow.scss
  client/src/components/ModalWindowWrapper/ModalWindowWrapper.jsx
  client/src/components/ModalWindowWrapper/__tests__/ModalWindow.spec.js
  client/src/components/NewArrivalsBlock/index.js
  client/src/components/ProductCard/AddToCartButton/index.js
  client/src/components/ProductCard/AddToCartButton/main.scss
  client/src/components/ProductCard/ProductCard.js
  client/src/components/UserInfoContent/UserInfoContent.jsx
  client/src/components/UserInfoContent/UserInfoContent.scss
  client/src/components/UserInfoInput/UserInfoInput.jsx
  client/src/components/UserInfoInput/UserInfoInput.scss
  client/src/constants/constants.js
  client/src/pages/Layout/Layout.js
  client/src/redux/action-creators/user-action-creator.js
  client/src/redux/action-types/userActionTypes.js
  client/src/redux/actions/user-actions.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/userReducer.js
  client/src/style/_colors.scss
  client/src/utils/interceptorResponse.js
  client/src/utils/isAuth.js
  client/src/utils/logout.js
  client/src/utils/signIn.js
  client/src/utils/signUp.js
Labels: feature, front-end

#280 Feature/filters url
  client/src/App.js
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.js
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/Filters.js
  client/src/components/Header/Header.scss
  client/src/components/Header/navigation.jsx
  client/src/components/ProductCatalog/ProductCatalog.js
  client/src/components/ProductsContainer/ProductsContainer.js
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/redux/action-creators/filter-action-creator.js
  client/src/redux/action-types/filterActionTypes.js
  client/src/redux/actions/filter-actions.js
  client/src/redux/reducers/filterReducer.js
Labels: feature, front-end

#281 fix/search-from-home
  client/src/components/Header/navigation.jsx
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/redux/reducers/filterReducer.js
Labels: fix, front-end
