Repository EasileleM/gd-ui-react-project, pull requests merged in 2019-10, with the labels that each got.

#23 Client initialization.
  .vscode/settings.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/components/index.js
  client/src/constants/index.js
  client/src/index.css
  client/src/index.js
  client/src/pages/index.js
  client/src/styles/_colors.scss
  client/src/styles/_fonts.scss
  client/src/styles/_mixins.scss
  client/src/styles/_variables.scss
  client/src/styles/main.scss
Labels: feature, front-end

#26 Added deploy.sh script
  deploy.sh
Labels: feature, front-end

#28 [feature] back-end-init
  .gitignore
  server/.gitignore
  server/database/cards.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/pages/api/card/[id].js
  server/pages/api/cards.js
  server/services/card-service.js
Labels: feature

#30 Fix/deploy fix
  .DS_Store
  .gitignore
  client/.gitignore
  client/Procfile
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/server.js
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  deploy.sh
  package.json
  server/Procfile
  server/package-lock.json
  server/package.json
  server/pages/index.js
Labels: back-end, fix, front-end

#40 Added sass. Removed redundant code from server.js. Changed css to scss.
  client/package-lock.json
  client/package.json
  client/server.js
  client/src/App.js
  client/src/App.scss
  client/src/index.js
  client/src/index.scss
Labels: feature, front-end

#43 Fix/dev script
  client/package.json
  client/server.js
Labels: fix

#53 Added global styles
  client/src/style/_colors.scss
  client/src/style/_fonts.scss
Labels: feature, front-end

#63 feature/47-1
  server/pages/api/items.js
Labels: back-end, feature

#73 Feature/best sales block
  client/src/components/ItemCardSmall/assets/Add_To_Cart_Ico.png
  client/src/components/ItemCardSmall/assets/star-empty.svg
  client/src/components/ItemCardSmall/assets/star.svg
  client/src/components/ItemCardSmall/index.js
  client/src/components/ItemCardSmall/main.scss
  client/src/components/index.js
Labels: feature, front-end

#45 Create homepage slider
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/components/slider/assets/Layer_1.png
  client/src/components/slider/buttons/index.js
  client/src/components/slider/buttons/main.scss
  client/src/components/slider/contentBlock/index.js
  client/src/components/slider/contentBlock/main.scss
  client/src/components/slider/imagesBlock/index.js
  client/src/components/slider/imagesBlock/main.scss
  client/src/components/slider/index.js
  client/src/components/slider/item/assets/bucket.png
  client/src/components/slider/item/index.js
  client/src/components/slider/item/main.scss
  client/src/components/slider/main.scss
  client/src/index.scss
  client/src/pages/home/index.js
  client/src/pages/home/main.scss
  client/src/style/_fonts.scss
Labels: feature, front-end

#54 Breakpoint variables
  client/src/style/_breakpoints.scss
  client/src/style/main.scss
Labels: feature, front-end

#64 Create footer
  client/src/assets/Payment_Images.png
  client/src/assets/link-dot-active.svg
  client/src/assets/link-dot.svg
  client/src/assets/logo.png
  client/src/components/footer/banking.js
  client/src/components/footer/footer.scss
  client/src/components/footer/index.js
  client/src/components/footer/links.js
  client/src/components/index.js
  client/src/style/_colors.scss
Labels: feature, front-end

#49 Create Ads block
  client/src/App.js
  client/src/components/AdsBlock/index.js
  client/src/components/AdsBlock/main.scss
  client/src/components/SaleItem/assets/bucket.png
  client/src/components/SaleItem/assets/square-1.svg
  client/src/components/SaleItem/assets/square-2.svg
  client/src/components/SaleItem/index.js
  client/src/components/SaleItem/main.scss
  client/src/components/SpecialOfferSection/index.js
  client/src/components/SpecialOfferSection/main.scss
  client/src/components/index.js
Labels: feature, front-end

#75 Fixes for pagination
  server/pages/api/items.js
Labels: back-end

#76 Feature/new arrivals styles
  client/src/App.js
  client/src/App.scss
  client/src/components/new-arrivals-block/new-arrivals-block.js
  client/src/components/new-arrivals-block/new-arrivals-block.scss
  client/src/components/product-card/components/color-selector/color-selector.js
  client/src/components/product-card/components/sizes-selector/sizes-selector.js
  client/src/components/product-card/product-card.js
  client/src/components/product-card/product-card.scss
  client/src/components/product-catalog/components/show-more-button/show-more-button.js
  client/src/components/product-catalog/components/show-more-button/show-more-button.scss
  client/src/components/product-catalog/product-catalog.js
  client/src/components/product-catalog/product-catalog.scss
  client/src/components/product-row/index.js
  client/src/components/product-row/product-row.js
  client/src/components/product-row/product-row.scss
  client/src/components/products-container/products-container.js
  client/src/components/products-container/products-container.scss
  client/src/components/section-header/section-header.scss
Labels: feature, front-end

#77 Mobile footer
  client/src/components/footer/footer.scss
Labels: fix, front-end

#80 initial layout
  client/src/App.js
  client/src/App.scss
  client/src/components/SaleItem/main.scss
  client/src/components/SpecialOfferSection/main.scss
  client/src/components/footer/footer.scss
  client/src/components/footer/index.js
  client/src/components/header/header.scss
  client/src/components/header/index.js
  client/src/components/index.js
  client/src/components/product-catalog/components/show-more-button/show-more-button.scss
  client/src/components/slider/contentBlock/main.scss
  client/src/components/slider/main.scss
  client/src/pages/home/index.js
  client/src/pages/home/main.scss
Labels: feature, front-end

#81 Products loading feature
  client/src/components/ItemCardSmall/index.js
  client/src/components/best-sales-block/best-sales-block.js
  client/src/components/best-sales-block/best-sales-block.scss
  client/src/components/best-sales-block/index.js
  client/src/components/new-arrivals-block/new-arrivals-block.js
  client/src/components/product-card/product-card.js
  client/src/components/product-catalog/components/show-more-button/show-more-button.js
  client/src/components/product-catalog/product-catalog.js
  client/src/components/product-small-container/index.js
  client/src/components/product-small-container/product-small-container.js
  client/src/components/product-small-container/product-small-container.scss
  client/src/components/products-container/products-container.js
Labels: feature, front-end

#82 Adaptation fix
  client/src/components/ItemCardSmall/main.scss
  client/src/components/index.js
  client/src/components/product-catalog/components/show-more-button/show-more-button.scss
  client/src/components/product-small-container/product-small-container.scss
  client/src/components/slider/contentBlock/main.scss
  client/src/components/slider/main.scss
  client/src/pages/home/index.js
Labels: fix, front-end
