Repository EasileleM/gd-ui-react-project, pull requests merged in 2019-12, with the labels that each got.

#279 Refactor/backend-db-mongoose
  client/src/components/LoginWindowContent/SignInForm/SignInForm.jsx
  client/src/components/LoginWindowContent/SignUpForm/SignUpForm.jsx
  client/src/constants/constants.js
  client/src/pages/Layout/Layout.js
  client/src/utils/isAuth.js
  client/src/utils/logout.js
  client/src/utils/signIn.js
  client/src/utils/signUp.js
  server/db/Models/filters.model.js
  server/db/Models/item.model.js
  server/db/Models/newsletter.model.js
  server/db/Models/slider.model.js
  server/db/Models/user.model.js
  server/db/db.js
  server/package-lock.json
  server/package.json
  server/pages/api/items/sales.js
  server/pages/api/newsletter.js
  server/pages/api/signUp.js
  server/passpoort-config.js
  server/server.js
  server/services/FilterService.js
  server/services/ItemsService.js
  server/services/NewsletterService.js
  server/services/SliderService.js
Labels: back-end, refactor

#293 feature: notification placing
  client/src/App.js
  client/src/App.scss
Labels: feature, front-end

#292 changed add to cart notification logic
  client/src/redux/thunks/cart/addItem.js
  client/src/redux/thunks/cart/updateItem.js
Labels: fix, front-end

#295 fixed modal window markup
  client/src/components/LoginWindowContent/LoginWindowContent.jsx
  client/src/components/LoginWindowContent/LoginWindowContentControls/LoginWindowContentControls.jsx
  client/src/components/LoginWindowContent/LoginWindowContentControls/LoginWindowContentControls.scss
  client/src/components/ModalWindowWrapper/CloseButton/CloseButton.scss
  client/src/components/ModalWindowWrapper/ModalWindow/ModalWindow.scss
Labels: fix, front-end

#296 fixed links in sale item
  client/src/components/SaleItem/SaleItem.js
Labels: fix, front-end

#299 changed login controls styles
  client/src/components/LoginWindowContent/LoginWindowContentControls/LoginWindowContentControls.scss
  client/src/components/ModalWindowWrapper/ModalWindow/ModalWindow.scss
Labels: fix, front-end

#300 feature/sign-up
  client/package.json
  client/server.js
  server/db/Models/user.model.js
  server/package-lock.json
  server/package.json
  server/passport-config.js
  server/server.js
Labels: back-end, feature

#303 initial refactor of cart logic
  client/package-lock.json
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/FavoritesItems/Item/Item.scss
  client/src/components/Filters/Filters.js
  client/src/components/ModalWindowWrapper/ModalWindowWrapper.jsx
  client/src/components/RedirectWrapper/RedirectWrapper.jsx
  client/src/index.js
  client/src/index.scss
  client/src/pages/Layout/Layout.js
  client/src/redux/action-creators/cart-action-creator.js
  client/src/redux/action-creators/error-action-creator.js
  client/src/redux/action-creators/favorites-action-creator.js
  client/src/redux/action-creators/filter-action-creator.js
  client/src/redux/action-creators/modalWindow-action-creator.js
  client/src/redux/action-creators/user-action-creator.js
  client/src/redux/action-types/cartActionTypes.js
  client/src/redux/action-types/errorActionTypes.js
  client/src/redux/action-types/favoritesActionTypes.js
  client/src/redux/action-types/filterActionTypes.js
  client/src/redux/action-types/modalWindowActionTypes.js
  client/src/redux/action-types/userActionTypes.js
  client/src/redux/actions/cart-actions.js
  client/src/redux/actions/error-actions.js
  client/src/redux/actions/favorites-actions.js
  client/src/redux/actions/filter-actions.js
  client/src/redux/actions/modalWindow-action.js
  client/src/redux/actions/user-actions.js
  client/src/redux/reducers/cartReducer.js
  client/src/redux/reducers/errorReducer.js
  client/src/redux/reducers/favoritesReducer.js
  client/src/redux/reducers/filterReducer.js
  client/src/redux/reducers/modalWindowReducer.js
  client/src/redux/reducers/userReducer.js
  client/src/redux/store.js
  client/src/redux/thunks/cart/addItem.js
  client/src/redux/thunks/cart/fetchItems.js
  client/src/redux/thunks/cart/removeItem.js
  client/src/redux/thunks/cart/setItems.js
  client/src/redux/thunks/cart/updateItem.js
  client/src/redux/thunks/favorites/addItem.js
  client/src/redux/thunks/favorites/fetchItems.js
  client/src/redux/thunks/favorites/removeItem.js
  client/src/redux/thunks/favorites/setItems.js
  client/src/redux/thunks/initialize.js
  client/src/style/main.scss
  client/src/utils/getAuthentificationInfo.js
  client/src/utils/interceptorResponse.js
  client/src/utils/isAuth.js
  client/src/utils/updateUserCart.js
  client/src/utils/updateUserFavorites.js
Labels: feature, front-end, refactor

#304 Feature/hide filters button
  client/public/locales/en-GB/translation.json
  client/public/locales/ru/translation.json
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.js
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.scss
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/Filters.js
  client/src/components/ProductCatalog/ProductCatalog.js
  client/src/pages/Search/Search.js
  client/src/pages/index.js
Labels: feature, front-end

#317 created show hide password functionality in sign up sign in form
  client/src/assets/eyeHide.svg
  client/src/assets/eyeShow.svg
  client/src/components/UserInfoInput/UserInfoInput.jsx
  client/src/components/UserInfoInput/UserInfoInput.scss
Labels: feature, front-end

#320 fixed product card
  client/src/components/ProductCard/ColorSelector/ColorSelector.jsx
  client/src/components/ProductCard/SizesSelector/SizesSelector.jsx
  client/src/components/ProductCard/SizesSelector/SizesSelector.scss
Labels: fix, front-end

#321 refactored frontend from previous sprint
  client/src/components/AddToCartButton/AddToCartButton.jsx
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/CartItems/CartItems.jsx
  client/src/components/CartItems/Item/Item.jsx
  client/src/components/FavoritesItems/FavoritesItems.jsx
  client/src/components/FavoritesItems/Item/Item.jsx
  client/src/components/Filters/FIlterSlider/FilterSlider.js
  client/src/components/Filters/FilterCheckbox/FilterCheckbox.js
  client/src/components/Filters/FilterRadio/FilterRadio.js
  client/src/components/Filters/FilterSearchBar/FilterSearchBar.js
  client/src/components/Header/UserButton/UserButton.jsx
  client/src/components/Header/cart.jsx
  client/src/components/Header/navigation.jsx
  client/src/components/ItemCardSmall/ItemCardSmall.js
  client/src/components/LoginWindowContent/SignInForm/SignInForm.jsx
  client/src/components/LoginWindowContent/SignUpForm/SignUpForm.jsx
  client/src/components/ModalWindowWrapper/ModalWindow/ModalWindow.jsx
  client/src/components/ModalWindowWrapper/ModalWindowWrapper.jsx
  client/src/components/Product/ProductInfo/ProductInfo.js
  client/src/components/SaleItem/SaleItem.js
  client/src/components/UserInfoContent/UserInfoContent.jsx
  client/src/pages/Layout/Layout.js
  client/src/pages/Search/Search.js
  client/src/redux/action-creators/cart/actions.js
  client/src/redux/action-creators/cart/addItem.js
  client/src/redux/action-creators/cart/removeItem.js
  client/src/redux/action-creators/cart/setItems.js
  client/src/redux/action-creators/cart/tests/addItem.spec.js
  client/src/redux/action-creators/cart/tests/fetchItems.spec.js
  client/src/redux/action-creators/cart/tests/removeItem.spec.js
  client/src/redux/action-creators/cart/tests/updateItem.spec.js
  client/src/redux/action-creators/cart/updateItem.js
  client/src/redux/action-creators/error/actions.js
  client/src/redux/action-creators/favorites/actions.js
  client/src/redux/action-creators/favorites/addItem.js
  client/src/redux/action-creators/favorites/removeItem.js
  client/src/redux/action-creators/favorites/setItems.js
  client/src/redux/action-creators/favorites/tests/addItem.spec.js
  client/src/redux/action-creators/favorites/tests/fetchItems.spec.js
  client/src/redux/action-creators/favorites/tests/removeItem.spec.js
  client/src/redux/action-creators/filter/actions.js
  client/src/redux/action-creators/initialize.js
  client/src/redux/action-creators/modalWindow/actions.js
  client/src/redux/action-creators/user/actions.js
  client/src/redux/action-creators/user/logout.js
  client/src/redux/action-creators/user/signIn.js
  client/src/redux/action-creators/user/signUp.js
  client/src/redux/reducers/cartReducer.js
  client/src/redux/reducers/errorReducer.js
  client/src/redux/reducers/favoritesReducer.js
  client/src/redux/reducers/filterReducer.js
  client/src/redux/reducers/modalWindowReducer.js
  client/src/redux/reducers/userReducer.js
  client/src/redux/store.js
  client/src/redux/thunks/logout.js
  client/src/utils/interceptorResponse.js
  client/src/utils/logoutFetch.js
  client/src/utils/signInFetch.js
  client/src/utils/signUpFetch.js
Labels: front-end, refactor

#324 updated auth endpoints and fixed cart and favorites fetch data
  client/src/redux/action-creators/cart/addItem.js
  client/src/redux/action-creators/cart/removeItem.js
  client/src/redux/action-creators/cart/updateItem.js
  client/src/redux/action-creators/favorites/addItem.js
  client/src/redux/action-creators/favorites/removeItem.js
  client/src/utils/getAuthentificationInfo.js
  client/src/utils/logoutFetch.js
  client/src/utils/signInFetch.js
  client/src/utils/signUpFetch.js
Labels: fix, front-end

#341 About page
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/assets/ArtemiiPhoto.png
  client/src/assets/AsmanPhoto.jpeg
  client/src/assets/MishaPhoto.jpeg
  client/src/assets/SashaKondPhoto.jpg
  client/src/assets/SashaPhoto.jpg
  client/src/assets/SavvaPhoto.jpeg
  client/src/assets/VovaKalachevPhoto.jpeg
  client/src/assets/VovaPhoto.jpeg
  client/src/assets/aboutImageHeader.jpeg
  client/src/components/FeedbackForm/FeedbackForm.jsx
  client/src/components/PersonBlock/PersonBlock.jsx
  client/src/components/PersonBlock/PersonBlock.scss
  client/src/components/PersonCard/PersonCard.jsx
  client/src/components/PersonCard/PersonCard.scss
  client/src/components/PictureWithHeader/PictureWithHeader.jsx
  client/src/components/PictureWithHeader/PictureWithHeader.scss
  client/src/components/TextAreaInput/TextAreaInput.scss
  client/src/pages/AboutPage/AboutPage.jsx
  client/src/pages/AboutPage/AboutPage.scss
  client/src/pages/ContactPage/ContactPage.scss
  server/src/db/Models/feedback.model.js
Labels: feature, front-end

#342 Refactor/user profile window
  client/public/locales/en-GB/translation.json
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/ModalWindowWrapper/ModalWindow/ModalWindow.scss
  client/src/components/UserInfoContent/UserInfoContent.jsx
  client/src/components/UserInfoContent/UserInfoContent.scss
  client/src/components/UserInfoInput/UserInfoInput.jsx
Labels: front-end, refactor

#343 Feature/hot deals translation
  client/public/locales/en-GB/translation.json
  client/public/locales/en/translation.json
  client/public/locales/ru/translation.json
  client/src/components/AddToCartButton/AddToCartButton.spec.js
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.jsx
  client/src/components/AddToFavoritesButton/AddToFavoritesButton.spec.js
  client/src/components/AddToFavoritesButton/tests/AddToFavoritesButton.spec.js
  client/src/components/AdsBlock/AdsBlock.js
  client/src/components/AdsBlock/AdsBlock.scss
  client/src/components/AdsBlock/AdsBlock.spec.js
  client/src/components/BestSalesBlock/BestSalesBlock.spec.js
  client/src/components/FavoritesItems/tests/FavoritesItems.spec.js
  client/src/components/Header/Header.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/Header/__tests__/Navigation.spec.js
  client/src/components/SpecialOfferSection/SpecialOfferSection.js
  client/src/pages/HotDealsPage/HotDealsPage.jsx
  server/src/services/AuthService.js
Labels: feature, front-end

#344 Feature/header links highlight
  client/src/components/Header/Navigation.jsx
Labels: feature, front-end

#345 fix/endpoint-for-all-items
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductsContainer/ProductsContainer.js
  server/src/services/ItemsService.js
Labels: back-end, fix

#346 fix/hot-deals-translation
  client/src/utils/loadHotDealsThisMonth.js
  client/src/utils/loadHotDealsThisWeek.js
Labels: fix, front-end
